version: '3.8'

services:
  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - micro-frontend-network

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - micro-frontend-network

networks:
  micro-frontend-network:
    driver: bridge
